from setuptools import setup, find_packages

setup(
    name="sillygram",
    version="0.0.0-alpha.1",
    packages=find_packages(),
    install_requires=[
        "aiofiles==23.2.1",
        "aiogram==3.10.0",
        "aiohttp==3.9.5",
        "aiosignal==1.3.1",
        "annotated-types==0.7.0",
        "attrs==23.2.0",
        "certifi==2024.7.4",
        "colorlog==6.8.2",
        "emoji==2.12.1",
        "frozenlist==1.4.1",
        "greenlet==3.0.3",
        "idna==3.7",
        "iniconfig==2.0.0",
        "langcodes==3.4.0",
        "language_data==1.2.0",
        "magic-filter==1.0.12",
        "marisa-trie==1.2.0",
        "multidict==6.0.5",
        "packaging==24.2",
        "pluggy==1.5.0",
        "pydantic==2.8.2",
        "pydantic_core==2.20.1",
        "pytest==8.3.4",
        "setuptools==72.1.0",
        "SQLAlchemy==2.0.31",
        "typing_extensions==4.12.2",
        "yarl==1.9.4",
    ],
    author="mivanoffka",
    author_email="mivanoffka@icloud.com",
    description="A lightweight and simple Telegram-bot framework based on aiogram",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/mivanoffka/SillyGram",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.12",
)
